In [3]:
import numpy as np

### Execution time of NumPy drastically lower than normal Python list:

In [4]:
%time for i in range(1000):np.arange(1000000)*2

CPU times: total: 1.17 s
Wall time: 2 s


In [3]:
%time for i in range(1000):list(range(1000000))*2

CPU times: total: 29.5 s
Wall time: 33.4 s


### Now let's take a look at np.append():

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.append(a,[[7,8,9]],axis=0) # add an array in row
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
c = np.append(b,[[10],[11],[12]],axis=1) # add an array in column
c

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

### As we got np.append(), we also have np.delete():

In [7]:
d = np.delete(a,0,axis=0) # delete an array a as row in line 0 [1,2,3]
d

array([[4, 5, 6]])

In [8]:
d = np.delete(b,2) # delete at (0,2) or 2
d

array([1, 2, 4, 5, 6, 7, 8, 9])